# datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://b5d0c81094add9:881afd78@us-cdbr-east-06.cleardb.net/heroku_58f0d5bebcbb63c?reconnect=true
    username: b5d0c81094add9
    password: 881afd78

# mybatis
mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml